name: FTP Test

on:
  push:
    branches:
      - toFTP

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test FTP Action
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: example.com
          username: test
          password: test
          local-dir: ./
          server-dir: /test/
